version: '3.8'

services:
  privacy-gateway:
    build: .
    container_name: privacy-gateway
    ports:
      - "10805:10805"
    volumes:
      - privacy-gateway-data:/app/data
    environment:
      # 基础配置
      - GATEWAY_PORT=10805
      - SENSITIVE_HEADERS=cf-,x-forwarded,proxy,via,x-request-id,x-trace,x-correlation-id,x-country,x-region,x-city

      # 持久化存储配置
      - PROXY_CONFIG_PERSIST=true
      - PROXY_CONFIG_FILE=/app/data/proxy-configs.json
      - PROXY_CONFIG_AUTO_SAVE=true

      # 代理配置（可选）
      # - DEFAULT_PROXY=http://proxy.example.com:8080
      # - PROXY_WHITELIST=proxy1.example.com,proxy2.example.com
      # - ALLOW_PRIVATE_PROXY=false

      # 管理功能配置（可选）
      # 取消注释下面的行来启用日志查看功能
      # - ADMIN_SECRET=your-admin-secret-here
      # - LOG_MAX_ENTRIES=1000
      # - LOG_MAX_BODY_SIZE=1024
      # - LOG_RETENTION_HOURS=24
      # - LOG_MAX_MEMORY_MB=50.0
      # - LOG_RECORD_200=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:10805/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 开发环境配置示例
  privacy-gateway-dev:
    build: .
    container_name: privacy-gateway-dev
    ports:
      - "10806:10805"
    volumes:
      - privacy-gateway-dev-data:/app/data
    environment:
      - GATEWAY_PORT=10805
      - SENSITIVE_HEADERS=cf-,x-forwarded,proxy,via
      - ADMIN_SECRET=12345678
      - LOG_RECORD_200=true
      - LOG_MAX_ENTRIES=2000
      - PROXY_CONFIG_PERSIST=true
      - PROXY_CONFIG_FILE=/app/data/proxy-configs.json
      - PROXY_CONFIG_AUTO_SAVE=true
    restart: unless-stopped
    profiles:
      - dev

# 数据卷定义
volumes:
  privacy-gateway-data:
    driver: local
  privacy-gateway-dev-data:
    driver: local
